site_name: banco - Documentation
site_url: https://docs.mythmc.ovh/banco
copyright: Copyright &copy; 2024 The myth-MC Team
repo_url: https://github.com/myth-MC/banco
repo_name: myth-MC/banco

theme:
  name: material
  # custom_dir: overrides
  logo: assets/logo.png
  favicon: assets/logo.png
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.instant
    - navigation.tabs
    - content.code.copy
    - content.code.annotate
    - content.tooltips
  palette:
    primary: brown
    scheme: slate

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tasklist:
      custom_checkbox: true
  - admonition
  - pymdownx.details

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/myth-MC/banco
    - icon: fontawesome/brands/discord
      link: https://discord.gg/
  version:
    provider: mike

nav:
  - Welcome: index.md
  - Getting started:
    - Quickstart: getting-started/index.md
    - Compatibility:
      - Server software: getting-started/compatibility/server-software.md
      - Other plugins: getting-started/compatibility/other-plugins.md
    - Configuration:
      - Adding or removing items: getting-started/configuration/adding-items.md
      - Translations: getting-started/configuration/translations.md
    - Commands and permissions: getting-started/commands.md
    - FAQ: getting-started/faq.md
  - Development:
    - Using the API: api/index.md
    - Accounts: api/accounts.md
    - Items: api/items.md
    - Storage: api/storage.md
    - Events:
      - api/events/BancoTransactionEvent.md
      - api/events/BancoAccountRegisterEvent.md
      - api/events/BancoAccountUnregisterEvent.md
      - api/events/BancoItemRegisterEvent.md
      - api/events/BancoItemUnregisterEvent.md
      - api/events/BancoStorageRegisterEvent.md
      - api/events/BancoStorageUnregisterEvent.md
